apiVersion: marketplace.kratix.io/v1alpha1
kind: app
metadata:
  namespace: default
  name: testing
spec:
  appConfig:
    image: syntasso/website
    lifecycle: prod
    requiresBucketBackend: true
    requiresDatabaseBackend: true
    servicePort: 80
